-- Table clients pour gérer les abonnements prerender
CREATE TABLE public.clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT,
  prerender_token TEXT UNIQUE NOT NULL DEFAULT gen_random_uuid()::TEXT,
  plan TEXT NOT NULL DEFAULT 'basic',
  allowed_domains TEXT[] NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Table prerender_logs pour tracker les renders
CREATE TABLE public.prerender_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  domain TEXT NOT NULL,
  url TEXT NOT NULL,
  cached BOOLEAN NOT NULL DEFAULT false,
  user_agent TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Index pour les stats rapides
CREATE INDEX idx_prerender_logs_client_created ON public.prerender_logs(client_id, created_at);
CREATE INDEX idx_prerender_logs_domain ON public.prerender_logs(domain);
CREATE INDEX idx_clients_token ON public.clients(prerender_token);

-- Enable RLS
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prerender_logs ENABLE ROW LEVEL SECURITY;

-- Policies pour clients (admins peuvent tout faire)
CREATE POLICY "Admins can view all clients" ON public.clients
  FOR SELECT USING (is_admin());

CREATE POLICY "Admins can insert clients" ON public.clients
  FOR INSERT WITH CHECK (is_admin());

CREATE POLICY "Admins can update clients" ON public.clients
  FOR UPDATE USING (is_admin());

CREATE POLICY "Admins can delete clients" ON public.clients
  FOR DELETE USING (is_admin());

-- Policies pour prerender_logs
CREATE POLICY "Admins can view all logs" ON public.prerender_logs
  FOR SELECT USING (is_admin());

CREATE POLICY "Service role can insert logs" ON public.prerender_logs
  FOR INSERT WITH CHECK (true);

-- Trigger pour updated_at sur clients
CREATE TRIGGER update_clients_updated_at
  BEFORE UPDATE ON public.clients
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Enable realtime pour les logs (stats en temps réel)
ALTER PUBLICATION supabase_realtime ADD TABLE public.prerender_logs;